<?php
	session_start();
	session_destroy();
	setcookie('admin_name','',time()-1);
	setcookie('admin_username','',time()-1);
	setcookie('teacher_name','',time()-1);
	setcookie('teacher_username','',time()-1);
	setcookie('student_name','',time()-1);
	setcookie('student_username','',time()-1);
	header('location:../index.php');
?>